FROM jenkins/jenkins:lts 
USER root
RUN apt-get update && apt-get install -y curl
USER jenkins
#COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
#RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
JENKINS_HOST ='{{$USERNAME}}':'{{$PASSWORD}}'@myhost.com:port
 curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/'

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
COPY admin-user.groovy /usr/share/jenkins/ref/init.groovy.d/admin-user.groovy
#COPY nexus-credentials.xml /var/jenkins_home/com.cloudbees.plugins.credentials.SystemCredentialsProvider.xml
ssh 
COPY pipeline-job.xml /var/jenkins_home/jobs/pipeline-job/config.xml
